export const europaSportOrder = [
   
   
   
  
    "rugby",
    "handball",
    "fencing",
    "croquet",
    "canoe_slalom",
    "equestrian_driving",
    "equestrian_jumping",
    "cycling_bmx_racing",
    "cycling_mountain_bike",
    "table_tennis",
    "judo",
    "diving",
    "karate",
    "cricket",
    "lacrosse",
    "polo",
    "rugby_sevens",
    "golf",
    "jeu_de_paume",
    "tennis",
    "modern_pentathlon",
    "tug-of-war",
    "art_competitions",
    "figure_skating",
    "skateboarding",
    "motorboating",
    "sailing",
    "rowing",
    "equestrian_eventing",
    "triathlon",
    "cycling_bmx_freestyle",
    "cycling_track",
    "archery",
    "boxing",
    "taekwondo",
    "racquets",
    "aeronautics",
    "alpinism",
    "artistic_gymnastics",
    "sport_climbing",
    "ice_hockey",
    "badminton",
    "hockey",
    "marathon_swimming",
    "cycling_road",
    "weightlifting",
    "wrestling",
    "volleyball",
    "softball",
    "athletics",
    "swimming",
    "artistic_swimming",
    "basque_pelota",
    "shooting",
    "equestrian_dressage",
    "canoe_marathon",
    "water_polo",
    "trampolining",
    "driving",
    "rhythmic_gymnastics",
    "equestrian_vaulting",
    "canoe_sprint",
    "surfing",
    "football",
    "baseball",
    "basketball",
    "3x3_basketball",
    "beach_volleyball",
];

export const europaCountryOrder = [
    "GEO",
    "AUT",
    "SWE",
    "LAT",
    "BOH",
    "GDR",
    "BLR",
    "SRB",
    "BEL",
    "SMR",
    "ITA",
    "ESP",
    "CRO",
    "SCG",
    "NED",
    "BUL",
    "DEN",
    "HUN",
    "TCH",
    "SLO",
    "GBR", //GBR
    "MNE",
    "SUI",
    "IRL",
    "ROU",
    "CZE",
    "GER",
    "LTU",
    "MKD",
    "SVK",
    "FRA",
    "EST",
    "YUG",
    "GRE",
    //ohne Kante
    "NOR",
    "LUX",
    "FIN",
    "FRG",
    "KOS",
    "ISL",
    "POR",
    "MDA",
    "UKR",
    "POL",
  

    
];
